name: Test and lint

on: [push]

jobs:
  node:
    name: Node 12
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync packages with cache
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules-

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: yarn lint --quiet --color

      - name: Run tests
        run: yarn run test --watchAll=false --colors --ci --coverage

      - name: Get coverage number
        uses: actions-ecosystem/action-regex-match@v2
        id: coverageNumber
        with:
          text: ${ cat coverage/lcov-report/index.html }
          regex: '(?<=>)[\d.]{1,6}(?=%\s*<)'

      - run: echo ${{ steps.coverageNumber.outputs.match }}
